[package]
name = "word-frequency"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.18", features = ["wrap_help", "derive"] }
hashbrown = "0.12.3"
natural = "0.5.0"
